sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 1234

#开发环境下的引用工具类
  alioss:
    endpoint: oss-cn-beijing.aliyuncs.com
    access-key-id: LTAI5tA1aEkkJKLtWbszXhEX
    access-key-secret: Pr4uQG5ZyUpoQudnAsztbTDO427j1B
    bucket-name: dongliangyu

  redis:
    host: localhost
    port: 6379
    password: 123456
    database: 10