sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 1234


  alioss:
    endpoint: http://s242nibj4.hb-bkt.clouddn.com/
    access-key-id: Bw9EeOI4-NGRQZWzt-wjxxLKj8aQSfaRMSt87Q5F
    access-key-secret: ZzxKBDTs5urAnIVAb0hN0c5GciyYo8AZJ-P1lP1u
    bucket-name: java17514

  redis:
    host: localhost
    port: 6379
    password: 123456
    database: 10